### ISSUE TITLE
Installing latest node-red-contrib-zeromq crashes node-red Docker Container

### ISSUE THREAD

**Issue by breif** [dceejay/node-red-contrib-zeromq#5]
Installation of the latest version of this node on the latest version of the node-red/node-red Docker image crashes the container.

Steps to reproduce:
1)  docker run -it -p 1880:1880 --name mynodered nodered/node-red
2) Open the Dashboard by navigating to http://localhost:1880
3) Menu -> Manage palette -> Install
4) Search for node-red-contrib-zeromq and click install

The node seems to install, but then if you wait about 10 - 30 seconds you'll see the "Lost connection to server" message and the container exits.

**Comment by dceejay** [comment]
The zeromq node includes binary components that may not compile correctly on the Alpine based container. You may need to manually build the debian based container instead. But I'll try to have a look later. It would help if you can provide any log from the install process.

**Comment by breif** [comment]
Thanks @dceejay, hasn't the node-red container always been based on Alpine? I've tried setting the logging in the settings.js to trace, but nothing helpful comes out. If I attach a volume to the /data folder I don't see any logs there either when the container stops. Is there another location that I should be looking in?

**Comment by dceejay** [comment]
Hi yes the main containers have always been on alpine. you should be able to see the install log while the node is installing via the editor UI.

**Comment by breif** [comment]
I was able to get some more information by:
1) Starting the container and mounted a volume to the /data folder (docker run -it -p 1880:1880 -v ${PWD}/data:/data --name mynodered nodered/node-red:latest)
2) Stopped the container (docker stop mynodered)
3) Updated the settings.js for trace logging
4) Restarted the container (docker start mynodered), and tried installing node-red-contrib-zeromq from the UI

It looks like it's expecting the zeromq npm package to be in /data/node_modules but can't find it because there is no node_modules folder inside /data. Shouldn't it be trying to install and look for the npm zeromq and node-red-contrib-zeromq packages inside the /usr/src/node-red/node_modules folder?

Screen shot and log file attached.

Thanks again for your help!

[2021-08-19T12_36_03_701Z-debug.log](https://github.com/dceejay/node-red-contrib-zeromq/files/7014448/2021-08-19T12_36_03_701Z-debug.log)
![node-red-error](https://user-images.githubusercontent.com/8548645/130071403-5b9014ad-df5b-4a1e-bda7-7ffd33effd1c.png)

**Comment by breif** [comment]
Hey @dceejay, I just wanted to check in and see if the additional logs helped to identify the issue at all, or if you had any thoughts?

**Comment by dceejay** [comment]
not had 5 mins to even look at it I'm afraid.

**Comment by sampras-intel** [comment]
I was trying this out and am facing the similar issue.
@dceejay Will there be a fix available anytime soon?
@breif you have any workarounds that you tried out?

**Comment by dceejay** [comment]
still not looked at it. - I still think you would probably need to build a debian based docker version to install it correctly as per the instructions in the node-red-docker project.

**Comment by jdeitmerg** [comment]
Had the same issue on nodered/node-red:2.2.3-12. Upgrading to nodered/node-red:3.0.2-16 (currently latest) fixed it.

Running the four steps in the initial description, I can't reproduce the problem :)

**Comment by dceejay** [comment]
closing as a) above  now seems to work b) works for me
